name: app
description: A Computer Scientists dream come true
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift:
  drift_dev: ^2.8.1
  file_picker: ^8.0.0+1
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  intl: ^0.19.0
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^2.0.0
  path_provider: ^2.0.9
  path: ^1.8.0
  riverpod: ^2.3.0
  provider: ^6.1.2
  motion_toast: ^2.9.1
  flutter_code_editor: ^0.3.1
  graphview: ^1.2.0
  webview_flutter: ^4.7.0
  giffy_dialog: ^2.1.0
  flutter_markdown: ^0.6.23
  highlight: ^0.7.0
  flutter_highlighter: ^0.1.1
  google_fonts: ^6.2.1
  animated_tree_view: ^2.2.0
  filter_list: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  flutter_blurhash: ^0.8.2
  inview_notifier_list: ^3.0.0
  fl_chart: ^0.67.0
  syncfusion_flutter_charts: ^25.1.40
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  table_calendar: ^3.1.1
  flutter_breadcrumb: ^1.0.1
  getwidget: ^4.0.0
  gap: ^3.0.1
  seo: ^0.0.7
  meta_seo: ^3.0.9
  fluttertoast: ^8.2.5
  flutter_easyloading: ^3.0.5
  logger: ^2.2.0
  http: ^1.2.1
  primer_progress_bar: ^0.4.1
  json_annotation: ^4.9.0
  url_strategy: ^0.2.0
  flutter_animate: ^4.5.0
  flutter_markdown_latex: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.1.8
  # We use this to compile the shared web worker for the web database. This dependency
  # isn't required for most apps. You only need it if you want to target the web, use
  # web workers for drift AND want to compile those web workers through `build_runner`.
  # Either way, using this package with Flutter requires a delicate setup described in
  # `build.yaml`.
  build_web_compilers: ^4.0.0
  build: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/icons/
    - assets/
