/// Flutter icons SDIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SDIcon
///      fonts:
///       - asset: fonts/SDIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class SDIcon {
  SDIcon._();

  static const _kFontFam = 'SDIcon';
  static const String? _kFontPkg = null;

  static const IconData ac_unit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threedee_rotation = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_photos = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_queue = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData album = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_inclusive = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_out = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_return = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_returned = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_turned_in = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
