/// Flutter icons SDIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SDIcon
///      fonts:
///       - asset: fonts/SDIcon.ttf
///
/// 
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class SDIcon {
  SDIcon._();

  static const _kFontFam = 'SDIcon';
  static const String? _kFontPkg = null;

  static const IconData spaced_reps_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guided_cintent = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ai_enabled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData best_tech = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curated_content = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geek = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guided_content = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData industry_leaders = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData problem_library = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData professional = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spaced_reps = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trusted = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_rect = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_text = IconData(0xf307, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf31a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_rect = IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
